# Converting of a csv file to json 
name: Converting cellanges from excel file to json

# Runs on pushes on commit
on:  
  # Runs on pushes targeting the default branch
  push:
    paths:
      - 'convert/together23_pieces_datenbank.xlsx'
  workflow_dispatch: # manual execute

# Jobs to execute
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pandas openpyxl
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
#      - name: Test with pytest
#        run: |
#          pytest
      - name: execute converter
        run: python convert/xlsx_to_json_csv.py

      - name: Upload artifact chellanges db
        uses: actions/upload-artifact@v3
        with:
          name: chellangesdb
          path: ./static/challanges.json

